### ISSUE TITLE
@ngneat/overview usage causes execution error

### ISSUE THREAD

**Issue by st-clair-clarke** [ngneat/overview#23]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

No error to be generated when @ngneat/overview is installed with pnpm

## Minimal reproduction of the problem with instructions
Install the library and run the application
## What is the motivation / use case for changing the behavior? The following error in app execution

```
[ERROR] No matching export in "node_modules/.pnpm/@ngneat+overview@6.0.0_@angular+core@17.0.5/node_modules/@ngneat/overview/fesm2022/ngneat-overview.mjs" for import "DynamicViewModule"

    node_modules/.pnpm/@ngneat+hot-toast@6.0.1_@angular+core@17.0.5_@ngneat+overview@6.0.0/node_modules/@ngneat/hot-toast/fesm2022/ngneat-hot-toast.mjs:6:37:
      6 │ import { isTemplateRef, isComponent, DynamicViewModule } from '@ngneat/overview';
        ╵                                      ~~~~~~~~~~~~~~~~~

/home/stclair/workspace/nx/mf/new/med-soft/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/@ngneat+hot-toast@6.0.1_@angular+core@17.0.5_@ngneat+overview@6.0.0/node_modules/@ngneat/hot-toast/fesm2022/ngneat-hot-toast.mjs:6:37: ERROR: No matching export in "node_modules/.pnpm/@ngneat+overview@6.0.0_@angular+core@17.0.5/node_modules/@ngneat/overview/fesm2022/ngneat-overview.mjs" for import "DynamicViewModule"
    at failureErrorWithLog (/home/stclair/workspace/nx/mf/new/med-soft/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
    at /home/stclair/workspace/nx/mf/new/med-soft/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
    at /home/stclair/workspace/nx/mf/new/med-soft/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 37,
        file: 'node_modules/.pnpm/@ngneat+hot-toast@6.0.1_@angular+core@17.0.5_@ngneat+overview@6.0.0/node_modules/@ngneat/hot-toast/fesm2022/ngneat-hot-toast.mjs',
        length: 17,
        line: 6,
        lineText: "import { isTemplateRef, isComponent, DynamicViewModule } from '@ngneat/overview';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/.pnpm/@ngneat+overview@6.0.0_@angular+core@17.0.5/node_modules/@ngneat/overview/fesm2022/ngneat-overview.mjs" for import "DynamicViewModule"'
    }
  ],
  warnings: []
}

Node.js v20.9.0


```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX v20.9.0

- Platform:  Linux

Others:

</code></pre>
IDE: Webstorm and Visual studio

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/overview/issues/23
